apiVersion: skaffold/v4beta3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: sayinmehmet47/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/client
      context: client
      sync:
        manual:
          - src: '**/*.tsx'
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
